application:
  threads: 3
  port: 5000
  history: 5
connection:
  host: 'localhost'
  port: 5433
  database: 'jacq_dev'
  user: 'databot'
  password: 'jacq'
bots:
  connection_tester:
    interval: "*/1 * * * *"
